//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPP.DL.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Autorizacion
    {
        public int AutorizacionId { get; set; }
        public int UsuarioId { get; set; }
        public int Codigo { get; set; }
        public int NaveId { get; set; }
        public int OperacionId { get; set; }
        public int EmbalajeId { get; set; }
        public int Bultos { get; set; }
        public double PesoManifestado { get; set; }
        public string Producto { get; set; }
        public int tipo { get; set; }
        public int estado { get; set; }
    
        public virtual Embalaje Embalaje { get; set; }
        public virtual Operacion Operacion { get; set; }
    }
}
