//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPP.DL.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Autorizacion
    {
        public Autorizacion()
        {
            this.Pesaje = new HashSet<Pesaje>();
        }
    
        public int AutorizacionId { get; set; }
        public string Codigo { get; set; }
        public int EmbalajeId { get; set; }
        public int OperacionId { get; set; }
        public decimal Peso { get; set; }
        public int NroBultos { get; set; }
        public short Estado { get; set; }
        public System.DateTime Fecha { get; set; }
        public int UsuarioId { get; set; }
        public int NaveId { get; set; }
        public string Producto { get; set; }
        public string Tipo { get; set; }
    
        public virtual Embalaje Embalaje { get; set; }
        public virtual Nave Nave { get; set; }
        public virtual Operacion Operacion { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual ICollection<Pesaje> Pesaje { get; set; }
    }
}
