//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPP.DL.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Conductor
    {
        public Conductor()
        {
            this.Pesaje = new HashSet<Pesaje>();
            this.Vehiculo = new HashSet<Vehiculo>();
        }
    
        public int ConductorId { get; set; }
        public string NroBrevete { get; set; }
        public string Nombres { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public string Estado { get; set; }
    
        public virtual ICollection<Pesaje> Pesaje { get; set; }
        public virtual ICollection<Vehiculo> Vehiculo { get; set; }
    }
}
