//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPP.DL.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contenedor
    {
        public int ContenedorId { get; set; }
        public short Estado { get; set; }
        public string Embarcadero { get; set; }
        public string AgenteAduana { get; set; }
        public string TipoMovimiento { get; set; }
        public string Codigo { get; set; }
        public Nullable<decimal> Tara { get; set; }
        public string NumeroViaje { get; set; }
        public Nullable<decimal> PesoManifiesto { get; set; }
        public string PrecintoAduanero { get; set; }
        public string Precinto1 { get; set; }
        public string Precinto2 { get; set; }
        public string Precinto3 { get; set; }
        public Nullable<System.DateTime> FechaMuelle { get; set; }
        public Nullable<System.DateTime> FechaBarco { get; set; }
        public Nullable<System.DateTime> FechaIzaje { get; set; }
        public int TipoContenedorId { get; set; }
        public int TamanoContenedorId { get; set; }
        public string EIR { get; set; }
        public string Ubicacion { get; set; }
        public Nullable<int> Autorizacion { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public int NaveId { get; set; }
    
        public virtual Nave Nave { get; set; }
        public virtual TamanioContenedor TamanioContenedor { get; set; }
        public virtual TipoContenedor TipoContenedor { get; set; }
    }
}
