//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPP.DL.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contenedor
    {
        public Contenedor()
        {
            this.Nave = new HashSet<Nave>();
        }
    
        public int ContenedorId { get; set; }
        public int NContenedor { get; set; }
        public int Consigna { get; set; }
        public double PesoManifiesto { get; set; }
        public int AgAduanas { get; set; }
        public int Reserva { get; set; }
        public int TipoId { get; set; }
        public int EstadoId { get; set; }
        public int Tara { get; set; }
        public int TipoContenedorId { get; set; }
        public int TamanoContenedorId { get; set; }
        public int NViaje { get; set; }
        public int EIR { get; set; }
        public int PAduanero { get; set; }
        public string Precinto1 { get; set; }
        public string Precinto2 { get; set; }
        public string Precinto3 { get; set; }
        public string Ubicacion { get; set; }
        public System.DateTime HIzaje { get; set; }
        public System.DateTime HBarco { get; set; }
        public System.DateTime HMuelle { get; set; }
    
        public virtual TamanoContenedor TamanoContenedor { get; set; }
        public virtual TipoContenedor TipoContenedor { get; set; }
        public virtual ICollection<Nave> Nave { get; set; }
    }
}
