//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPP.DL.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Eje
    {
        public Eje()
        {
            this.Vehiculo = new HashSet<Vehiculo>();
        }
    
        public int EjeId { get; set; }
        public string Codigo { get; set; }
        public string Nombre { get; set; }
        public int PesoMaximo { get; set; }
    
        public virtual ICollection<Vehiculo> Vehiculo { get; set; }
    }
}
