//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPP.DL.DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BDParacasEntities : DbContext
    {
        public BDParacasEntities()
            : base("name=BDParacasEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AuditoriaPesaje> AuditoriaPesaje { get; set; }
        public virtual DbSet<Autorizacion> Autorizacion { get; set; }
        public virtual DbSet<Conductor> Conductor { get; set; }
        public virtual DbSet<Contenedor> Contenedor { get; set; }
        public virtual DbSet<Embalaje> Embalaje { get; set; }
        public virtual DbSet<GuiaRemision> GuiaRemision { get; set; }
        public virtual DbSet<MovimientoPesaje> MovimientoPesaje { get; set; }
        public virtual DbSet<Nave> Nave { get; set; }
        public virtual DbSet<Operacion> Operacion { get; set; }
        public virtual DbSet<Pesaje> Pesaje { get; set; }
        public virtual DbSet<Reporte> Reporte { get; set; }
        public virtual DbSet<Rol> Rol { get; set; }
        public virtual DbSet<TamanioContenedor> TamanioContenedor { get; set; }
        public virtual DbSet<TipoContenedor> TipoContenedor { get; set; }
        public virtual DbSet<TipoVehiculo> TipoVehiculo { get; set; }
        public virtual DbSet<Turno> Turno { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<Vehiculo> Vehiculo { get; set; }
    
        public virtual ObjectResult<Sp_ReportePesaje_Result> Sp_ReportePesaje()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_ReportePesaje_Result>("Sp_ReportePesaje");
        }
    }
}
