//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPP.DL.DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BDParacasEntities : DbContext
    {
        public BDParacasEntities()
            : base("name=BDParacasEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Autorizacion> Autorizacion { get; set; }
        public virtual DbSet<Conductor> Conductor { get; set; }
        public virtual DbSet<Contenedor> Contenedor { get; set; }
        public virtual DbSet<Eje> Eje { get; set; }
        public virtual DbSet<Embalaje> Embalaje { get; set; }
        public virtual DbSet<GuiaRemision> GuiaRemision { get; set; }
        public virtual DbSet<Nave> Nave { get; set; }
        public virtual DbSet<Operacion> Operacion { get; set; }
        public virtual DbSet<RolUsuario> RolUsuario { get; set; }
        public virtual DbSet<TamanoContenedor> TamanoContenedor { get; set; }
        public virtual DbSet<TipoContenedor> TipoContenedor { get; set; }
        public virtual DbSet<Turno> Turno { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<Vehiculo> Vehiculo { get; set; }
        public virtual DbSet<Pesaje> Pesaje { get; set; }
    }
}
