//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPP.DL.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovimientoPesaje
    {
        public int MovimientoPesajeId { get; set; }
        public int PesajeId { get; set; }
        public System.DateTime Fecha { get; set; }
        public decimal Peso { get; set; }
        public string Tipo { get; set; }
        public int UsuarioId { get; set; }
        public string TipoRepesaje { get; set; }
        public string Estado { get; set; }
    
        public virtual Pesaje Pesaje { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
