//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPP.DL.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nave
    {
        public Nave()
        {
            this.Autorizacion = new HashSet<Autorizacion>();
            this.Contenedor = new HashSet<Contenedor>();
            this.Pesaje = new HashSet<Pesaje>();
        }
    
        public int NaveId { get; set; }
        public string Nombre { get; set; }
        public decimal PesoTotal { get; set; }
        public string Estado { get; set; }
    
        public virtual ICollection<Autorizacion> Autorizacion { get; set; }
        public virtual ICollection<Contenedor> Contenedor { get; set; }
        public virtual ICollection<Pesaje> Pesaje { get; set; }
    }
}
