//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPP.DL.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pesaje
    {
        public int VehiculoId { get; set; }
        public int ConductorId { get; set; }
        public int AutorizacionId { get; set; }
        public int Peso { get; set; }
    
        public virtual Conductor Conductor { get; set; }
    }
}
