//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPP.DL.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reporte
    {
        public int ReporteId { get; set; }
        public int UsuarioId { get; set; }
        public System.DateTime Fecha { get; set; }
        public int TurnoId { get; set; }
        public string EstadoFiltro { get; set; }
    
        public virtual Turno Turno { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
