//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPP.DL.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoContenedor
    {
        public TipoContenedor()
        {
            this.Contenedor = new HashSet<Contenedor>();
        }
    
        public int TipoContenedorId { get; set; }
        public string Descripcion { get; set; }
    
        public virtual ICollection<Contenedor> Contenedor { get; set; }
    }
}
