//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPP.DL.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public Usuario()
        {
            this.AuditoriaPesaje = new HashSet<AuditoriaPesaje>();
            this.Autorizacion = new HashSet<Autorizacion>();
            this.MovimientoPesaje = new HashSet<MovimientoPesaje>();
            this.Pesaje = new HashSet<Pesaje>();
            this.Reporte = new HashSet<Reporte>();
        }
    
        public int UsuarioId { get; set; }
        public string Codigo { get; set; }
        public string Password { get; set; }
        public string Estado { get; set; }
        public int RolId { get; set; }
    
        public virtual ICollection<AuditoriaPesaje> AuditoriaPesaje { get; set; }
        public virtual ICollection<Autorizacion> Autorizacion { get; set; }
        public virtual ICollection<MovimientoPesaje> MovimientoPesaje { get; set; }
        public virtual ICollection<Pesaje> Pesaje { get; set; }
        public virtual ICollection<Reporte> Reporte { get; set; }
        public virtual Rol Rol { get; set; }
    }
}
