//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPP.DL.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehiculo
    {
        public int VehiculoId { get; set; }
        public string Placa { get; set; }
        public string Carrete { get; set; }
        public int EjeId { get; set; }
    
        public virtual Eje Eje { get; set; }
    }
}
